CREATE TABLE shop.tags (
    tag_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tag_name text NOT NULL UNIQUE
);

CREATE TABLE shop.customer_tags (
    customer_id integer NOT NULL REFERENCES shop.customers(customer_id) ON DELETE CASCADE,
    tag_id integer NOT NULL REFERENCES shop.tags(tag_id) ON DELETE CASCADE,
    assigned_at date NOT NULL DEFAULT current_date,
    PRIMARY KEY (customer_id, tag_id)
);

