-- CAPSTONE: rank customers by completed-order lifetime revenue within their segment.
-- Build one row per completed order, then customer metrics, then rank.
-- Include customers with at least one completed order only.
-- Columns:
--   segment
--   revenue_rank: DENSE_RANK within segment, highest revenue first
--   customer_id
--   company_name
--   acquisition_channel: metadata channel, or 'unknown'
--   completed_orders
--   lifetime_revenue rounded to 2 decimals
--   first_order
--   last_order
-- Return only ranks 1 and 2. Sort by segment, revenue_rank, customer_id.

-- TODO
