\set ON_ERROR_STOP on

DROP SCHEMA IF EXISTS training CASCADE;
DROP SCHEMA IF EXISTS shop CASCADE;

CREATE SCHEMA shop;
CREATE SCHEMA training;
SET search_path TO shop, public;

CREATE TABLE customers (
    customer_id   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_name  text NOT NULL,
    email         text UNIQUE,
    phone         text,
    country       text,
    segment       text NOT NULL CHECK (segment IN ('smb', 'midmarket', 'enterprise')),
    referred_by   integer REFERENCES customers(customer_id),
    created_at    date NOT NULL,
    metadata      jsonb NOT NULL DEFAULT '{}'::jsonb
);

CREATE TABLE categories (
    category_id   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_name text NOT NULL UNIQUE
);

CREATE TABLE products (
    product_id    integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku           text NOT NULL UNIQUE,
    product_name  text NOT NULL,
    category_id   integer NOT NULL REFERENCES categories(category_id),
    unit_price    numeric(10, 2) NOT NULL CHECK (unit_price >= 0),
    discontinued  boolean NOT NULL DEFAULT false,
    attributes    jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at    date NOT NULL
);

CREATE TABLE employees (
    employee_id   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name    text NOT NULL,
    last_name     text NOT NULL,
    manager_id    integer REFERENCES employees(employee_id),
    department    text NOT NULL,
    hire_date     date NOT NULL,
    salary        numeric(10, 2) NOT NULL CHECK (salary > 0)
);

CREATE TABLE orders (
    order_id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id      integer NOT NULL REFERENCES customers(customer_id),
    sales_rep_id     integer REFERENCES employees(employee_id),
    order_date       date NOT NULL,
    status           text NOT NULL CHECK (status IN ('pending', 'processing', 'completed', 'cancelled', 'refunded')),
    shipping_country text NOT NULL,
    shipped_at       date,
    notes            text,
    CHECK (shipped_at IS NULL OR shipped_at >= order_date)
);

CREATE TABLE order_items (
    order_id    integer NOT NULL REFERENCES orders(order_id) ON DELETE CASCADE,
    product_id  integer NOT NULL REFERENCES products(product_id),
    quantity    integer NOT NULL CHECK (quantity > 0),
    unit_price  numeric(10, 2) NOT NULL CHECK (unit_price >= 0),
    discount    numeric(4, 3) NOT NULL DEFAULT 0 CHECK (discount BETWEEN 0 AND 1),
    PRIMARY KEY (order_id, product_id)
);

CREATE TABLE payments (
    payment_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id   integer NOT NULL REFERENCES orders(order_id),
    paid_at    date NOT NULL,
    amount     numeric(10, 2) NOT NULL CHECK (amount > 0),
    method     text NOT NULL CHECK (method IN ('card', 'bank_transfer', 'paypal')),
    status     text NOT NULL CHECK (status IN ('pending', 'succeeded', 'failed', 'refunded'))
);

CREATE TABLE warehouses (
    warehouse_id   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    warehouse_name text NOT NULL UNIQUE,
    country        text NOT NULL
);

CREATE TABLE inventory (
    warehouse_id   integer NOT NULL REFERENCES warehouses(warehouse_id),
    product_id     integer NOT NULL REFERENCES products(product_id),
    units_in_stock integer NOT NULL CHECK (units_in_stock >= 0),
    reorder_level  integer NOT NULL CHECK (reorder_level >= 0),
    last_stocked_at date NOT NULL,
    PRIMARY KEY (warehouse_id, product_id)
);

COMMENT ON SCHEMA shop IS 'Commerce dataset used by the SQL playground';
COMMENT ON COLUMN order_items.discount IS 'Fraction from 0.000 to 1.000, applied to unit_price';

